- name: Landaal - MikroTik Backup Automation
  hosts: mikrotik
  connection: paramiko
  gather_facts: no
  ignore_errors: yes
  vars_files:
    - vars.yml

  connection: paramiko
  user: "{{ftpuser_var}}"
  gather_facts: no
  tasks:
   - name: Maak backup van Mikrotik
     routeros_command:
       commands:
          - /system backup save name {{inventory_hostname}}

   - name: exporteer configuration naar tekst file
     routeros_command:
       commands:
           - /export file={{inventory_hostname}}

   - name: FTP backup file
     routeros_command:
       commands:
           - /tool fetch address={{ftpserver_var}} src-path={{inventory_hostname}}.backup user={{ftpuser_var}} password={{ftppass_var}} mode=ftp dst-path=/Mikrotik-backups/{{inventory_hostname}}_{{date}}.backup upload=yes

   - name: FTP export config
     routeros_command:
       commands:
           - /tool fetch address={{ftpserver_var}} src-path={{inventory_hostname}}.rsc user={{ftpuser_var}} password={{ftppass_var}} mode=ftp dst-path=/Mikrotik-backups/{{inventory_hostname}}_{{date}}.rsc upload=yes

      
   - name: send completion alert Telegram
     include_tasks: playbooks/send_comp_alert.yml
     tags: always
     when:
      - task_failed is not defined

   - name: send failure alert Telegram
     include_tasks: playbooks/send_failure_alert.yml
     tags: always
     when:
       - task_failed is defined
       - task_failed == true


